# Generated by Django 2.1.4 on 2019-02-24 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfirmationKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('min_members', models.PositiveIntegerField(default=1)),
                ('max_members', models.PositiveIntegerField(default=1)),
                ('is_registration_on', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.UUIDField(default=uuid.uuid4)),
                ('study_year', models.PositiveIntegerField()),
                ('degree', models.CharField(blank=True, max_length=30, null=True)),
                ('branch', models.CharField(blank=True, max_length=30, null=True)),
                ('country', models.CharField(blank=True, max_length=40, null=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Others/Not Specified')], null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='media/resumes')),
                ('institute_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.Institute')),
                ('referred_by', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='referred', to='website.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('all_members', models.ManyToManyField(related_name='team_members', to='website.Profile')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_creator', to='website.Profile')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Event')),
            ],
        ),
        migrations.CreateModel(
            name='TeamInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Event')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to='website.Profile')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Team')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to='website.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='passwordresetkey',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.Profile'),
        ),
        migrations.AddField(
            model_name='emailconfirmationkey',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.Profile'),
        ),
    ]
