# Generated by Django 2.1.5 on 2019-03-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_profile_complete',
            field=models.BooleanField(default=False),
        ),
    ]
