# Generated by Django 2.1.5 on 2019-03-24 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20190323_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidReferral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_people', to='website.Profile')),
                ('to', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral', to='website.Profile')),
            ],
        ),
    ]
