# Generated by Django 2.1.5 on 2019-04-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20190324_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='access_code',
            field=models.CharField(default='uninitialized', max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='membership',
            name='is_accepted',
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('team', 'profile')},
        ),
        migrations.AlterUniqueTogether(
            name='validreferral',
            unique_together={('by', 'to')},
        ),
    ]
