# Generated by Django 2.1.5 on 2019-04-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20190405_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(default='IN', max_length=4),
        ),
        migrations.AlterField(
            model_name='profile',
            name='institute_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.DeleteModel(
            name='Institute',
        ),
    ]
