# Generated by Django 2.1.5 on 2019-04-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20190410_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='institute_type',
            field=models.IntegerField(choices=[(0, 'College'), (1, 'School'), (2, 'Professional')], null=True),
        ),
    ]
