# Generated by Django 2.1.5 on 2019-04-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_profile_institute_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default='def'),
            preserve_default=False,
        ),
    ]
