# Generated by Django 2.1.5 on 2019-04-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20190412_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='institute_type',
            field=models.IntegerField(choices=[(0, 'School'), (1, 'College'), (2, 'Professional')], null=True),
        ),
    ]
