# Generated by Django 2.1.5 on 2019-04-14 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20190413_0216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeforces', models.CharField(blank=True, max_length=100, null=True)),
                ('codechef', models.CharField(blank=True, max_length=100, null=True)),
                ('hackerrank', models.CharField(blank=True, max_length=100, null=True)),
                ('hackerearth', models.CharField(blank=True, max_length=100, null=True)),
                ('analyticsvidya', models.CharField(blank=True, max_length=100, null=True)),
                ('topcoder', models.CharField(blank=True, max_length=100, null=True)),
                ('dev_folio', models.CharField(blank=True, max_length=100, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='handles', to='website.Profile')),
            ],
        ),
    ]
