# Generated by Django 2.1.5 on 2019-04-14 17:47

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20190414_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='referral_code',
            field=models.CharField(default=website.models.generate_referral_code, max_length=50, unique=True),
        ),
    ]
