# Generated by Django 2.1.5 on 2019-04-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20190416_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='referral_count',
            field=models.IntegerField(default=0),
        ),
    ]
