# Generated by Django 2.1.5 on 2019-05-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_auto_20190420_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='CA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('institute_name', models.CharField(max_length=200)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
    ]
