# Generated by Django 2.1.5 on 2019-05-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_ca'),
    ]

    operations = [
        migrations.AddField(
            model_name='ca',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
