# Generated by Django 2.1.5 on 2019-06-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_ca_caid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
