# Generated by Django 2.1.5 on 2019-06-25 13:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_auto_20190625_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='ca',
            name='last_updated',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
