# Generated by Django 2.1.5 on 2020-03-27 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
