# Generated by Django 2.1.5 on 2020-03-27 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_profile_fcm_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
