# Generated by Django 2.1.5 on 2019-03-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifiedaccount',
            name='provider',
            field=models.CharField(choices=[('facebook.com', 'Facebook'), ('google.com', 'Google'), ('github.com', 'Github'), ('password', 'Email')], max_length=15),
        ),
    ]
