# Generated by Django 2.1.5 on 2021-12-03 20:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('display_projects', '0003_auto_20211204_0110'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='project',
            new_name='ProjectModel',
        ),
    ]
