# Generated by Django 2.1.5 on 2021-12-06 07:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('display_projects', '0005_auto_20211206_1253'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='ProjectComment',
        ),
        migrations.AlterUniqueTogether(
            name='projectcomment',
            unique_together={('user', 'project')},
        ),
    ]
