# Generated by Django 2.1.5 on 2021-12-06 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display_projects', '0006_auto_20211206_1254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcomment',
            options={},
        ),
    ]
