# Generated by Django 2.1.5 on 2021-12-06 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display_projects', '0007_auto_20211206_1302'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectcomment',
            unique_together=set(),
        ),
    ]
